# Generated by Django 4.0.6 on 2023-05-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilArty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='estimated_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
